# Generated by Django 3.2.17 on 2023-02-04 14:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerSupport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.userprofile')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('age', models.IntegerField(default=0)),
                ('license_type', models.CharField(choices=[('BP', 'BUILDING PERMIT'), ('RL', 'RECOGNITION LICENSE'), ('SL', 'SUBDIVISION LICENSE'), ('EL', 'EXTENSION LICENSE'), ('LP', 'LAND MOVEMENT AND PARCEL LICENSE'), ('DC', 'DEMOLITION AND CONSTRUCRION LICENSE'), ('SR', 'Structural Reinforcement')], max_length=2)),
                ('customer_support', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='slcd_logic.customersupport')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.userprofile')),
            ],
        ),
    ]
